### ISSUE TITLE
Typos on www.sqrlfor.net

### ISSUE THREAD

**Issue by hahndorf** [TechLiam/SQRL-For-Dot-Net-Standard#27]
There are a bunch of typos on the home page, I don't think the page is part of this repository, so here are the fixes you should make:

- Are => Our
- there => their
- referance => reference
- your => you are
- licanced => license

**Comment by TechLiam** [comment]
Thanks, Hahndorf that site is going to have a whole new design soon so I have been putting off updating it with corrected text as it will be changing thanks for the pointers though.
