### ISSUE TITLE
Invalid JSON when supporting multiple URLs

### ISSUE THREAD

**Issue by josegomez** [TechLiam/SQRL-For-Dot-Net-Standard#28]
If you setup the plugin to have multiple Authentication paths. 
Such as
`options.OtherAuthenticationPaths = new OtherAuthenticationPath[]
                    {
                        new OtherAuthenticationPath()
                        {
                            AuthenticateSeparately=true,
                            Path="/Hi"
                        },
                        new OtherAuthenticationPath()
                        {
                            AuthenticateSeparately=true,
                            Path="/Hi2"
                        }
                    };
`

Then the helper generates invalid JSON at 
?login-sqrl?Helper URL

There is a comma missing after the redirectURL and before the OtherURls array
![image](https://user-images.githubusercontent.com/420837/70474358-70eea900-1aa0-11ea-89e3-72209265b6c5.png)

**Comment by TechLiam** [comment]
Ah thanks, ill patch this in the next few day

**Comment by TechLiam** [comment]
This is now fixed and was released in 1.4.1
